Refactoring
- Removed useless run function
- Remove need for -r flag. VM name is now specified last
- Improved error handling
- Updated usage accordingly

diff --git a/easy-emu b/easy-emu
--- a/easy-emu
+++ b/easy-emu
@@ -28,16 +28,17 @@ FLAGS=("-enable-kvm -sdl -cpu host -vga virtio") # Default flags, updated in sta
 
 # Check qemu is installed
 if [ -z $QEMU ] || [ -z $QEMU_IMG ]; then
-    echo "ERROR: qemu is not installed"
+    echo -e "\nERROR: qemu is not installed.\n"
     exit 1
 fi
 
 function usage() {
     echo "
-Usage: easy-emu [options]
+Usage: easy-emu [options] [VM name]
 
--create     | -c [VM name]     Create a new virtual machine 
--run        | -r [VM name]     Start an existing VM
+-help       | -h               Show this help message
+-host                          Show some basic host system info
+-create     | -c               Create a new virtual machine 
 -cpus       | -C [Num cpus]    Specify number of cpus. Default is host max
 -sockets    | -S [Num sockets] Specify number of sockets. Default is host max
 -iso        | -i [Path]        Path to OS ISO image
@@ -64,15 +65,15 @@ Resolution:       $SCREEN_RES
     exit 0
 }
 
-# Start qemu VM
-function run_vm() {
-    $QEMU ${@}
-}
-
 # Create a qcow2 virtual HDD
 function create_disk() {
+    if [ -e ${VARS[name]} ]; then
+        echo -e "\n${VARS[name]} already exists.\n"
+        exit 1
+    fi
+
     if [ -z "${VARS[iso]}" ]; then
-        echo "No ISO image supplied"
+        echo -e "\nNo ISO image supplied.\n"
         exit 1
     fi 
     if [ -z "${VARS[size]}" ]; then
@@ -82,11 +83,13 @@ function create_disk() {
     fi     
 }
 
-
 if [ $# -lt 1 ]; then
     usage
     exit 0
 else
+    
+    VARS+=( [name]=${@: -1} )
+
     while [ $# -gt 0 ]; do
         case $1 in
             --help | -help | -h)
@@ -95,22 +98,9 @@ else
             --host | -host)
                 host
             ;;
-            --run | -run | -r)
-                if [ ! -e $2 ]; then
-                    echo "VM not found"
-                    exit 1
-                fi
-                VARS+=( [name]=$2 )
-                shift; shift
-            ;;
             --create | -create | -c)
-                if [ -e $2 ]; then
-                    echo "$2 already exists"
-                    exit 1
-                fi
                 F_CREATE=1
-                VARS+=( [name]=$2 )
-                shift; shift
+                shift
             ;;
             --fullscreen | -fullscreen | -f)
                 FLAGS+=( "-full-screen" )
@@ -118,7 +108,7 @@ else
             ;;
             --iso | -iso | -i)
                 if [ ! -e $2 ]; then  
-                   echo "ISO not found" 
+                   echo -e "\nISO not found.\n" 
                    exit 1
                 fi 
                 VARS+=( [iso]=$2 )
@@ -146,36 +136,50 @@ else
                         UEFI_IMG=$i
                     fi
                 done
-                if [ -z UEFI_IMG ]; then
-                    echo "Unable to find OVMF. Is it installed?"
+                if [ -z $UEFI_IMG ]; then
+                    echo -e "\nUnable to find OVMF. Is it installed?\n"
                     exit 1
                 fi
                 FLAGS+=( "-bios $UEFI_IMG" )
                 shift
             ;;
+            ${VARS[name]}) # Ignore VM name
+                shift
+            ;;
             *)
                 usage
-            ;;
-            -test)
-                shift
             ;;
         esac
     done
 fi
 
 function start() {    
-    
-    if [ $F_CREATE -gt 0 ]; then
-        create_disk
-    fi
-
+    # Update flags 
     FLAGS+=( "-name ${VARS[name]}" "-drive file=${VARS[name]}" "-m ${VARS[ram]}" "-smp sockets=${VARS[sockets]},cores=${VARS[cpus]}" )
 
     if [ -n "${VARS[iso]}" ]; then
         FLAGS+=( "-cdrom ${VARS[iso]}" )
     fi
     
-    run_vm ${FLAGS[@]}
+    # Check name was given at end
+    for i in "${!VARS[@]}"; do
+        if [[ "${VARS[$i]}" == "${VARS[name]}" && "$i" != "name" ]]; then
+            usage
+        fi
+    done
+    
+    # Create disk if needed 
+    if [ $F_CREATE -gt 0 ]; then
+        create_disk
+    fi
+    
+    # Check for VM and start
+    if [ ! -e ${VARS[name]} ]; then
+        echo -e "\nUnable find ${VARS[name]}. Check path or use -c to create it.\n"
+        exit 1
+    fi
+
+    $QEMU ${FLAGS[@]}
 }
 
 start &
